add attention
hiqdev/hipanel-faq pull request #8
Opened 2021-10-18 11:29 UTC by bladeroot

2021-10-20 09:55 UTC, strorch approved these changes

2021-11-03 08:14 UTC, SilverFire requested changes

2021-11-03 08:14 UTC, SilverFire commented on src/faq_source/01-dns/03-errors/01-the-object.php
> +    <b class="text text-danger">Attention!!!</b> If this NSes provided by hoster you should ask him about creating them in "native" regisry
```suggestion
    Seeing this error when using the name servers, another company provided to you? Then, please, contact that company support team and ask to create these NSs in their domain control panel.
```

2021-11-03 08:14 UTC, SilverFire commented on src/faq_source/01-dns/03-errors/ru/01-the-object.php
> +    <b class="text text-danger">Внимание!!!</b> Если имена NS-серверов предоставлены хостером, Вам стоит обратиться к хостеру с требованием создать соответствующие записи в реестре
```suggestion
    Видите эту ошибку при использовании серверов имен, предоставленных вам другой компанией? Тогда, пожалуйста, свяжитесь со службой поддержки этой компании и попросите создать эти NS в панели управления их доменом.
```

2021-11-03 08:15 UTC, merged