HP-919 Undefined variable
hiqdev/hipanel-faq pull request #9
Opened 2022-08-11 14:18 UTC by gadezist

'label' не використовується в цьому класі, а метод приватний

2022-08-15 16:23 UTC, hiqsol reviewed
@tafid посмотри плиз, внимательно

2022-08-17 09:03 UTC, tafid requested changes

2022-08-17 09:03 UTC, tafid commented on src/menus/FaqMenu.php
> -        $indexFile = "$path/index.php";
не совсем согласен что нужно столько кода выкинуть

2022-08-17 10:04 UTC, gadezist commented on src/menus/FaqMenu.php
> -        $indexFile = "$path/index.php";
Повернув

2022-08-19 09:04 UTC, merged